name: i3mrec
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.13.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.7
  - numpy=1.26.4
  - numba=0.60.0
  - scipy
  - pandas
  - tqdm
  - pip
  - pip:
    - tensorboardX
    - faiss-cpu  # 如果有GPU可以改为 faiss-gpu
